return {}

-- lua/plugins/copilot.lua

-- TEMP: disable
-- return {
-- 	"zbirenbaum/copilot.lua",
-- 	cmd = "Copilot",
-- 	event = "InsertEnter",
-- 	config = function()
-- 		require("copilot").setup({
-- 			panel = {
-- 				enabled = true,
-- 				auto_refresh = false,
-- 				keymap = {
-- 					jump_prev = "[[",
-- 					jump_next = "]]",
-- 					accept = "<C-u>",
-- 					refresh = "gr",
-- 					open = "<M-CR>",
-- 				},
-- 				layout = {
-- 					position = "bottom", -- | top | left | right
-- 					ratio = 0.4,
-- 				},
-- 			},
-- 			suggestion = {
-- 				enabled = true,
-- 				auto_trigger = true,
-- 				debounce = 75,
-- 				keymap = {
-- 					accept = "<C-l>",
-- 					accept_word = false,
-- 					accept_line = false,
-- 					-- TODO fix
-- 					next = "<M-]>",
-- 					prev = "<M-[>",
-- 					dismiss = "<M-e>",
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
