setopt autocd
# Profiling
# zmodload zsh/zprof

ZSH_THEME="minimal"

plugins=(
	# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
  zsh-autosuggestions
	# https://github.com/zsh-users/zsh-syntax-highlightings/blob/master/INSTALL.md
  zsh-syntax-highlighting
)

export EDITOR=nvim

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PRIV=$HOME/.priv/zsh.priv.env
export MYVIMRC=$HOME/.vimrc

export DOTFILES=$HOME/.dotfiles
export ZFILES=$HOME/.dotfiles/zsh

# General terminal
source $ZSH/oh-my-zsh.sh
source $ZFILES/git.zsh
source $ZFILES/macos.zsh

# Developer tools
source $ZFILES/aliases.zsh
source $ZFILES/func.zsh
source $ZFILES/docker.zsh
source $ZFILES/fzf.zsh

# Languages 
source $ZFILES/node.zsh
source $ZFILES/ruby.zsh
source $ZFILES/go.zsh
source $ZFILES/rust.zsh
source $ZFILES/python.zsh

source $PRIV

# zprof
