setopt autocd

ZSH_THEME="ubuntu"

plugins=(
	# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
  zsh-autosuggestions
	# https://github.com/zsh-users/zsh-syntax-highlightings/blob/master/INSTALL.md
  zsh-syntax-highlighting
)

export EDITOR=nvim

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PRIV=$HOME/.zshrcpriv
export MYVIMRC=$HOME/.vimrc

export DOTFILES=$HOME/.dotfiles
export ZFILES=$HOME/.dotfiles/zsh

source $ZSH/oh-my-zsh.sh
source $ZFILES/alias.zsh
source $ZFILES/language.zsh
source $ZFILES/func.zsh
source $ZFILES/vcs.zsh
source $ZFILES/docker.zsh
source $ZFILES/fzf.zsh
source $ZFILES/python.zsh
source $ZFILES/rust.zsh
source $ZFILES/macos.zsh

source $PRIV
